version: '3.8'
services:
  app:
    build:
      context: .
    container_name: App
    ports:
      - '${APP_PORT}:8080'
    environment:
      ConnectionString: Server=Db;Port=${DB_PORT};Username=${DB_USER};Password=${DB_PASSWORD};Database=${DB_NAME}
    depends_on:
      database:
        condition: service_started
    networks:
      - app-network
  database:
    image: postgres:16.0
    container_name: db
    ports:
      - '${DB_PORT}:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - app-network
    volumes:
      - DbData:/var/lib/postgresql/data
networks:
  app-network:

volumes:
  DbData: