@bookingId=

### Post Booking

POST {{HOST}}/Booking
Content-Type: application/json

{
  "startDate": "2024-01-29T15:58",
  "endDate": "2024-01-30T15:58",
  "ownerMail": "ejemplo2@ejemplo",
  "invitations": [
    "nuevo@ejemplo"
  ]
}

### Get Booking

GET {{HOST}}/Booking?email=ejemplo2@ejemplo
Accept: application/json

### Put Booking
PUT {{HOST}}/Booking?bookingId={{bookingId}}&email=nuevo@ejemplo
Content-Type: application/json